### PR TITLE
Added section Repositories no longer maintained

### PR DESCRIPTION
**Pull request by pgaudet**

### CODE REVIEW

**Comment by lpalbou** [comment]
I would however create a more descriptive page for downloads since the [current.geneontology.org](http://current.geneontology.org) is not very intuitive. Perhaps not as "complex" as [example](http://git.dhimmel.com/gene-ontology/), but at least detailing the different types of files we provide and a link to the appropriate folder

**Comment by kltm** [comment]
Downloads is currently part of products/ :
http://current.geneontology.org/products/pages/downloads.html

**Comment by pgaudet** [comment]
Nice !

**Comment by pgaudet** [comment]
Species: Can we change the names in parenthesis to be more easy to understand ? 
Databases: Can we link the name of the database instead of having it twice ? 
(for eg: "dictyBase (dictybase, Ddis)" would become 
<link>dictyBase</link>, Dictyostelium discoideum

Thanks, Pascale

**Comment by lpalbou** [comment]
Nice indeed ! 

@kltm so I assume the plan is to integrate this page in the repo before deployment so we can refers to it with a local url ?

**Comment by kltm** [comment]
We'll do a theme/menu match when we're there, but it will be a remote link.

**Pull request merged**
