### PR TITLE
Update downloads.md

### PR DESCRIPTION
**Pull request by suzialeksander**
Adding link to current

@pgaudet was there a conversation about keeping current.geneontoloy a little hidden to avoid confusion? 
@kltm is neutral about showing/hiding this line.

### CODE REVIEW

**Comment by pgaudet** [comment]
I would **not** merge this. 

The 'http://current.geneontology.org/'  folder contains a bunch of stuff not intended for users. So I would rather not expose the entire folder. 

Links in the downloads page (http://current.geneontology.org/products/pages/downloads.html) go to 'current', that seems sufficient, isn't it?

**Comment by pgaudet** [comment]
Alternatively, we can link 'deeper' in /current: 

For ontology files: http://current.geneontology.org/ontology/index.html
For annotation files: http://current.geneontology.org/annotations/index.html


What do you think ?

**Comment by kltm** [comment]
Noting, if used, those URLs would be:
http://current.geneontology.org/ontology/
http://current.geneontology.org/annotations/

**Comment by kltm** [comment]
Also noting, that as part of the pipeline cleanup project, we'll be improving the file layout of the archives and making them less confusing.

**Comment by suzialeksander** [comment]
closing as wontfix, this page should no longer be accessible

**Pull request closed without merging**
