### PR TITLE
Update introduction-go-resource.md

### PR DESCRIPTION
**Pull request by suzialeksander**
@kltm can you check the permalink/redirects are formatted correctly

@pgaudet is "introduction-to-go" ok? "introduction-to-go-knowledgebase" seems unnecessarily long

### CODE REVIEW

**Comment by kltm** [comment]
@suzialeksander I would note that there are some things with trailing slashes and some things without; is there a difference in function and how the links are created here?

**Comment by suzialeksander** [comment]
no difference.  the old-permalink-now-redirect was copy/pasted.  i've removed the trailing slash on the new permalink, am I ok to remove it on the old?

**Comment by kltm** [comment]
@suzialeksander Well, I was going to test it with a local build, but I'm having trouble building a working environment (probably a worry for sooner rather than later).
I think you're okay to copy and paste whatever, but as soon as it's live, I'd check the live page, note how things behave, and edit accordingly to make sure we're not leaking over to geneontology.github.io.

**Comment by pgaudet** [comment]
This is OK for me, thanks

**Pull request merged**
