### PR TITLE
Update contributing-go.md

### PR DESCRIPTION
**Pull request by suzialeksander**
@pgaudet and/or @vanaukenk- I've added a few notes for new contributing groups in the "Contributing new GO annotations" section.  Can you check to make sure it's correct but not over/under promising.  Ideally there will be another doc (in progress) that will have more detailed instructions once they've contacted us, plus the MOU.  This is just to let groups like the beetle group have an idea before they start/contact us.

### CODE REVIEW

**Comment by pgaudet** [comment]
@suzialeksander This is a great start, but there are a few points I'd like to like to clarify. Can you make a Google doc with this, so we can comment and discuss?

**Comment by suzialeksander** [comment]
I've added it to https://docs.google.com/document/d/1AgDzxOTjsGvtyyvpSGayIcO1ljA8uPIhJzInzc-D4K8/edit?usp=sharing, or I think you can edit this draft before it's merged back.

**Comment by suzialeksander** [comment]
@pgaudet were there any changes? I didn't see any edits, the text is under the 2022-12-16 call

**Comment by suzialeksander** [comment]
Also noting this is similar to the unlisted-but-technically-accessible https://geneontology.org/docs/submitting-go-annotations/

**Comment by pgaudet** [comment]
HI Suzi, 

This is a good start - much better than what we have now. I reorganized the order and added /removed a couple of things: 

Our recommendation for annotating novel genomes is to [submit transcripts to NCBI](https://www.ncbi.nlm.nih.gov/). These submissions will reach [UniProt](https://www.uniprot.org/){:target="blank"}, where [InterPro2GO](https://www.ebi.ac.uk/GOA/InterPro2GO){:target="blank"} will automatically create ([IEA](/docs/guide-go-evidence-codes/)) GO annotations. These annotations will be made available in a future GO release. GO does not recommend *that* groups create their own IEAs with internal tools due to reproducibility and accuracy concerns. ~Please contact us if you have questions.~

Research groups who wish to generate manual GO annotations *from experimental data*- for instance new annotations for genes of a species that is not currently annotated in GO or annotating specific genes for a given biological research domain- can contribute these annotations to the GO knowledgebase. *Please contact us early in your project to establish the data exchange process between your group and GO. GO will make sure you have access to the proper documentation and training materials to ensure ~we can accept~ your annotations meet the GO guidelines.

GO annotation files must be in [GAF 2.2](/docs/go-annotation-file-gaf-format-2.2/) and contains:  
- UniProt IDs, or IDs that can be mapped to UniProt, for each annotated entity
- precise & informative GO terms for each entity, taking in to account taxon constraints and term restrictions
- PMID of the published literature describing the methods and findings
- *an evidence code [insert link to doc]*
- other mandatory elements are listed in the [GAF 2.2 file documentation[](/docs/go-annotation-file-gaf-format-2.2/).


~Contributing groups are responsible for maintaining their set of annotations long-term unless we can incorporate them into another group (e.g. GOA).  Please contact us early in your project to ensure we can accept your annotations and that you can commit to attending training and other required calls.~

*Please contact us if you have questions.*


----

Let me know if that sounds OK. 
Thanks, Pascale

**Pull request merged**
