### PR TITLE
Created external-mapping-file-format

### PR DESCRIPTION
**Pull request by pgaudet**

### CODE REVIEW

**Comment by suzialeksander** [comment]
Would this be better in the wiki? Otherwise OK to add/merge

**Comment by pgaudet** [comment]
I think this needs to be in the public documentation, since we provide annotations using these mappings, We need to explain what they are. @ukemi what do you think ?

**Comment by ukemi** [comment]
I agree that we should have some public documentation for this so people understand the origin of these annotations.

**Comment by suzialeksander** [comment]
Ok, I think this info should be added onto the top of the download-mappings.md page.  Currently, this external mapping doc name isn't OK to save (is the whole "http://geneontology.org/page/external-mapping-file-format" address, not a doc in /docs/_docs).

**Comment by pgaudet** [comment]
We need to be consistent - In other places the documentation is separate from the actual downloads.  Please keep separate for now. 

@suzialeksander If the doc is not OK to merge can you please close this Pull Request and create the correct file? 

Thanks, Pascale

**Comment by suzialeksander** [comment]
go-docs/docs/_docs/external-mapping-file-format.md  created.

**Pull request closed without merging**
