### PR TITLE
Suzi branch 1

### PR DESCRIPTION
**Pull request by suzialeksander**
Is this the best way to add images back to the pages? Or do I just put these links directly in the appropriate .md file? I've never played around with images on GH, but looks like it's using the png still hosted on geneontology.org, not saved on GH. 

 (source: https://www.tilcode.com/add-a-screenshot-to-your-github-repo-readme-md/)

### CODE REVIEW

**Comment by kltm** [comment]
Note: https://github.com/geneontology/go-docs/pull/24#issuecomment-425530313
Images should be added to this repo, and linked locally.

**Comment by pgaudet** [comment]
I have no idea how to add image in markdown. @lpalbou can you help us ? 

Thanks, Pascale

**Comment by cmungall** [comment]
https://guides.github.com/features/mastering-markdown/

See Examples, click images

**Comment by lpalbou** [comment]
Yes, the way to include images in markdown is:
`Alt Text`

Example: 
`part of and has part relations`

The `url` can refer to either local or external files, but because the Drupal will be retired, they won't exist externally so we are better off integrating them now to the repo and using their local url. It will also help testing true standalone version of the site and see if it works.

However, @kltm , do we follow the old hierarchy for files (e.g. /sites/default/files/u425/diag-allsome-haspart.gif) or can we define a new, simpler and more intuitive hierarchy such as /assets/pics/diag-allsome-haspart.gif ?

I don't think we need more hierarchy than:
* /assets/pics/
* /assets/docs/

**Comment by kltm** [comment]
No need to follow the old hierarchy. I'd even make it flatter than your suggestion, but whatever works.

**Comment by suzialeksander** [comment]
So on https://github.com/geneontology/go-docs/blob/master/docs/_docs/contributing-go.md, due to the (massive) size of the image, the only way I could resize was 
`[](http://geneontology.org/contributing-go-term)`

otherwise the icons were completely different sizes.  Is this OK? `Alt Text` worked when I didn't need to resize.  I just used the addresses from geneontology.org.

I will probably edit contributing-go.md soon, with more instructions on submitting annotations- but am trying to get these images & docs in order before Thurs.

**Comment by lpalbou** [comment]
@suzialeksander when we have local copies of those images and you only need them in a smaller size, it would be better to resize them and store them to that minimal required size. 

It may seem unimportant but you still download the full resolution image, which aside from slowing the site, may cause trouble and costs if generalized: the site will be hosted on GH which has a 100GB data transfer limit / month. For 50k visitors / month, it means only 2MB / visit.. So if your single image is 1MB instead of 50kb, in that context, that's actually a lot.

In that same spirit of speed / lowering data transfer, unless you need transparency, it would be better to use JPEG.

**Notes**: 
* after resizing them, you can still set the width & height to ensure they are displayed the way you want.
* @kltm we could also run a small prog to automatically resize unreasonably large images. That would be ok if we consider we are not supposed to have very large image to download or display

**Comment by kltm** [comment]
@lpalbou Run any resizing script in the repo that you want. Large things that we want can always be hosted elsewhere.

**Comment by suzialeksander** [comment]
@kltm  @lpalbou, you may be vastly overestimating my GitHub/computery skills.  I don’t know where the website images are currently hosted locally, where they need to be (if different), or what different sizes to make them. I can probably resize but not really sure how I’d do that yet so it would probably take me longer than it needs to. 

So, this probably isn't happening yet:
>The url can refer to either local or external files, but because the Drupal will be retired, they won't exist externally so we are better off integrating them now to the repo and using their local url.

**Pull request closed without merging**
