### PR TITLE
Include stats

### PR DESCRIPTION
**Pull request by lpalbou**
The following needs to be further discussed before merging:
* storing & access to go-stats-summary.json files (currently added in assets/stats). Ideally, there would be an API route providing the list of releases and the URLs to stats for each
* link to the new stats page from the main page, ontology overview and annotation overview pages

Ticket: https://github.com/geneontology/geneontology.github.io/issues/175

### CODE REVIEW

**Comment by kltm** [comment]
@suzialeksander Guessing merge should wait on stats availability, which is being hammered on now.

**Comment by lpalbou** [comment]
I would advocate to merge this PR now since this is a working version. The URL to fetch the stats from the current.geneontology.org instead of the temporary URL can be fixed later when the pipeline complete a full release (@kltm any update on when ?)

**Comment by suzialeksander** [comment]
I'm tempted to wait on this merge as it's a bit odd to put a live URL that's known to be dead, unless I'm misunderstanding what is in this PR? Maybe splitting it up would have been better? @kltm @lpalbou

**Comment by lpalbou** [comment]
@suzialeksander this PR is about the [new stats page](http://www5.geneontology.xyz/stats.html) and how to access it from the GO site.

The URL to fetch the data is live, not dead, but the intent is to change it when a full release is out. It's a single line of code and I see no technical reason to delay the deployment of the stats page.

Note the stats shown on the the main page are also provided by an external URL since the data wasn't stored in GO releases at the time either.

When the next release is out, my intent is to fix both URLs to point to the current GO release stats.

**Comment by lpalbou** [comment]
Merging this.

Need to take care of the two URLs to update after the GO release with the stats (https://github.com/geneontology/geneontology.github.io/issues/183)

**Pull request merged**
